// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZ0VX6iQhMuDDnYO7X4HA9A3yAlufuAk',
    appId: '1:600773355102:web:9981ce99d18157f305f6cf',
    messagingSenderId: '600773355102',
    projectId: 'task-management-app-e0c20',
    authDomain: 'task-management-app-e0c20.firebaseapp.com',
    storageBucket: 'task-management-app-e0c20.firebasestorage.app',
    measurementId: 'G-DGK22VHE3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7hN3lYGun_GakIB8UFYdWjsuHJ4BDtno',
    appId: '1:600773355102:android:12c3e838ecf56f3e05f6cf',
    messagingSenderId: '600773355102',
    projectId: 'task-management-app-e0c20',
    storageBucket: 'task-management-app-e0c20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnhld5NmOB9zKQKos6d0FVv2J0pjIxx18',
    appId: '1:600773355102:ios:29a2cfd0eecd217d05f6cf',
    messagingSenderId: '600773355102',
    projectId: 'task-management-app-e0c20',
    storageBucket: 'task-management-app-e0c20.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnhld5NmOB9zKQKos6d0FVv2J0pjIxx18',
    appId: '1:600773355102:ios:29a2cfd0eecd217d05f6cf',
    messagingSenderId: '600773355102',
    projectId: 'task-management-app-e0c20',
    storageBucket: 'task-management-app-e0c20.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvZ0VX6iQhMuDDnYO7X4HA9A3yAlufuAk',
    appId: '1:600773355102:web:72d538d0db85f18805f6cf',
    messagingSenderId: '600773355102',
    projectId: 'task-management-app-e0c20',
    authDomain: 'task-management-app-e0c20.firebaseapp.com',
    storageBucket: 'task-management-app-e0c20.firebasestorage.app',
    measurementId: 'G-CT8M3TDSXH',
  );
}
